gameInit_table={
	"iframe.utils.displayUtils",
	"iframe.utils.shader",
	"iframe.utils.utf8",
	"xml.core",
	"iframe.decode.decode",
	"iframe.decode.actHide",
	"iframe.decode.actShow",
	"iframe.decode.actPlace",
	"iframe.decode.actDelay",
	"iframe.decode.actSequence",
	"iframe.decode.actMove",
	"iframe.decode.actScale",
	"iframe.decode.actRotate",
	"iframe.decode.actFade",
	"iframe.decode.actBlink",
	"iframe.decode.actTint",
	"iframe.decode.actOrbitCamera",
	"iframe.decode.actRepeat",
	"iframe.decode.actEase",
	"iframe.decode.actCallBack",
	"cjson=cjson.core",
	"FlashAni=iframe.ui.flashAni",
	"FlashAniGroup=iframe.ui.flashAniGroup",
	"UILayer=iframe.ui.uiLayer",
	"Scene3D=iframe.ui.scene3D",
	"ScrollLayer=iframe.ui.scrollLayer",
	"RTFLayer=iframe.ui.rtfLayer",
	"LayOutLayer=iframe.ui.layOutLayer",
	"iframe.init",


	"socket = socket" ,
	"youme",
	"version",
	"diffinit",
	"platform",
	"data.const",
	"data.event",
	"utils",
	"data.banshuReview",
	"data.conf.flaPacker",
	"data.conf.flaRelation",
	"data.conf.cooperateSkill",
    "data.conf.advanceColor",
    "data.conf.flaSound",
	"data.db.params_client",
	"data.db.pet",
	"data.db.pet_upgrade",
	"data.db.pet_exp",
	"data.db.pet_skill_upgrade" ,
	"data.db.iap" ,
	"data.db.pet_shop",
    "data.db.miningelement" ,
    "data.db.soulboxshardinfo" ,
    "data.db.miningproject",
    "data.db.mine_stage",
    "data.db.teach",
    "data.db.turnscore",
    "data.db.crosstreasurehall",
    "data.db.minematerialbuyinfo",
    "data.db.constellationstar",
    "data.db.cavechallengeinfo",
    
    
    
	"design.skillDesc" ,
	"data.db" ,
	"data.panel",
	"data.scene" ,
	"data.words" ,
	"data.speWords" ,
	"data.item" ,
	"data.netCommand",
	"data.net",
	"data.netError",
	"data.net.netAtlas",
	"data.net.netCard",
	"data.net.netShop",
	"data.net.netDrawCard",
	"data.net.netParser",
	"data.net.netArena",
	"data.net.netOther",
	"data.net.netChat",
	"data.net.netFriend",
	"data.net.netPet",
	"data.net.netTask",
	"data.net.netActivity",
	"data.net.netFamily",
	"data.net.netSignin",
	"data.net.netMail",
	"data.net.netBath",
	"data.net.netTrainRoom",
	"data.net.netSpirit",
	"data.net.netCrusade",
	"data.net.netRank",
	"data.net.netMining",
    "data.net.netWeapon",
    "data.net.netFamilyWar",
    "data.net.netWorldBoss",
    "data.net.netServerBattle",
    -- "data.net.netTower",
    "data.net.netTown",
    "data.net.netTreasure",
    "data.net.netLuckWheel",
    "data.net.netMiningAtlas",
    "data.net.netFamilyStage",
    "data.net.netFoodFight",
    "data.net.netTreasureHunt",
    "data.net.netRichman",
    "data.net.netConstellation",
	"data.card",
	"data.pet",
	"data.redpos",
	"data.attChange",
	"data.soullife",
	"data.localNotify",
	"data.digmine",
	"data.serverBattle",
	"data.mineAtlas",
	"data.treasureHunt",
    "data.constellation",

	"design.guidestep.firstAtlas",
	"design.guidestep.draw",
	"design.guidestep.equip",
	"design.guidestep.secondAtlas",
	"design.guidestep.thirdAtlas", 
	"design.guidestep.upgradeCard", 
	"design.guidestep.recurit",
    "design.guidestep.onlineGift",
    "design.guidestep.firstBattle",
    "design.guidestep.taskReward",
    "design.guidestep.atlasPass",
    "design.guidestep.atlasNotice",
    

	"design.guideData",
	"design.story",
	"design.guide",
	"design.params",
	"StoryLayer=design.storyPanel",
	"GuideLayer=design.guidePanel",


	"PlayerTarget=data.battle.battlePlayerTarget",
	"PlayerCard=data.battle.battlePlayerCard",
    "PlayerPet=data.battle.battlePlayerPet",
    "SpiritChain=data.battle.spiritChain",
	"data.battle.battleData",
	"data.battle.battleLogic",
	"data.battle.battle",


	"view.unlock.unlock",
	"view.unlock.unlockArena",
	"view.unlock.unlockShop",
	"view.unlock.unlockEliteAtlas",
	"view.unlock.unlockTurnGold",
	"view.unlock.unlockTask",
	"view.unlock.unlockSkill",
	"view.unlock.unlockFriend",
	"view.unlock.unlockActGold",
	"view.unlock.unlockActExp",
	"view.unlock.unlockActPetSoul",
	"view.unlock.unlockActEquSoul",
	"view.unlock.unlockFamily",
	"view.unlock.unlockPetTower",
	"view.unlock.unlockPet",
	"view.unlock.unlockPetSkill",
	"view.unlock.unlockPetStar",
	"view.unlock.unlockAtlasBox",
	"view.unlock.unlockBattleSpeedUp",
	"view.unlock.unlockAct",
	"view.unlock.unlockTower",
	"view.unlock.unlockExpedition",
	"view.unlock.unlockTeamPos",
	"view.unlock.unlockPetFormation",
	"view.unlock.unlockSweep",
	"view.unlock.unlockQuickUpgrade",
	"view.unlock.unlockFund",
	"view.unlock.unlockShop2",
	"view.unlock.unlockShop3",
	"view.unlock.unlockTrainVipRoom",
	"view.unlock.unlockTrainRoom",
	"view.unlock.unlockBath" ,
	"view.unlock.unlockBattleAuto",
	"view.unlock.unlockXunXian",
	"view.unlock.unlockChat",
	"view.unlock.unlockSpiritQuick",
	"view.unlock.unlockCrusade",
	"view.unlock.unlockDrawSoul",
	"view.unlock.unlockMineProj.lua",
	"view.unlock.unlockMine.lua",
	"view.unlock.unlockWeapon.lua",
	"view.unlock.unlockShopSoul.lua",
    "view.unlock.unlockWorldBoss.lua",
    "view.unlock.unlockBossAtlas.lua",
    "view.unlock.unlockServerBattle",
    "view.unlock.unlockSweepOne",
    "view.unlock.unlockTreasure",
    "view.unlock.unlockHalo",
    "view.unlock.unlockTreasureHunt",
    "view.unlock.unlockLootFood",
    "view.unlock.unlockConstellation",
    "view.unlock.unlockActItemAwake",
    "view.unlock.unlockRiseStar",

	"view.switch.switch.lua",
	"view.switch.switchCardYear.lua",
	"view.switch.switchCardMonth.lua",

	"data.data" ,
	"data.dataVip" ,

	"Account=data.account",
	"EditModeLayer=view.edit.editModeLayer",
	"EditLayer=view.edit.editLayer",
	"EditRoleLayer=view.edit.editRoleLayer",
	"EditUVLayer=view.edit.editUVLayer",
	"EditObjItem=view.edit.editObjItem",
	"EditTimeline=view.edit.editTimeline",
	"EditActionItem=view.edit.editActionItem",
	"view.edit.editUtils",
	"EnterLayer=view.login.enterLayer",
	"LoginPanel=view.login.loginPanel",
	"WXBindPanel=view.login.wxBindPanel",
	"WXLoginPanel=view.login.wxLoginPanel",
	"WXLoginPasswordPanel=view.login.wxLoginPasswordPanel",

	"CardAwakePreviewItem=view.card.cardAwakePreviewItem" ,

	"ShowItemPoolLayer=view.common.showItemPool",

	"AtlasEliteFlopPanel=view.atlas.atlasEliteFlopPanel",
	"AtlasEliteFlopTabPanel=view.atlas.atlasEliteFlopTabPanel",
	"AtlasEliteFlopTabItem=view.atlas.atlasEliteFlopTabItem",
	"view.atlas.atlasEliteFlopCore",

    "ServerItem=view.login.serverItem",
    "ServerRole=view.login.serverRole",
    "ServerArea=view.login.serverArea",
	"ServerPanel=view.login.serverPanel",
	"NoticeboardPanel=view.login.noticeboardPanel",
	"NoticeboardItem=view.login.noticeboardItem",

	"PayItem=view.pay.payItem",
	"PayMissPanel=view.pay.payMissPanel",
	"PayMissItem=view.pay.payMissItem",
	
	"FirstEnterLayer=view.login.firstEnterLayer",
	"GetRewardPanel=view.common.getRewardPanel",
	"ConfirmLayer=view.common.confirmLayer",
	"NoticeLayer=view.common.noticeLayer",
	"RollNoticeLayer=view.common.rollNoticeLayer",
    "NoRollNoticeLayer=view.common.noRollNoticeLayer",
	"MsgWinLayer=view.common.msgWinLayer",
	"WaitingLayer=view.common.waitingLayer",
	"LoadingLayer=view.common.loadingLayer",

	"json = json",

-- }

-- --开始游戏时加载的lua
-- startGameInit_table = {	
	"data.db.vip",
	"data.db.turngold",
	"data.db.chapter",
	"data.db.box",
	"data.db.boxitem",
	"data.db.arenareward",
	"data.db.actstage",
	"data.db.actstageinfo",
	"data.db.buff",
	"data.db.card_exp",
	"data.db.card",
	"data.db.cardgrade",
	"data.db.cardquality",
	"data.db.equ_price",
	"data.db.equcompound",
	"data.db.equipitem",
	"data.db.equipment",
	"data.db.item",
	"data.db.skill",
	"data.db.user_exp",
	"data.db.skill_upgrade_price",
	"data.db.monster",
	"data.db.stage",
	"data.db.relation" ,
	"data.db.relation_title" ,
	"data.db.pet_stage" ,
	"data.db.gift_common" ,
	"data.db.daytask" ,
	"data.db.achievetype",
	"data.db.achieve",
	"data.db.familywdlv",
	"data.db.sign",
	"data.db.sign_vip",
	"data.db.signreward",
	"data.db.icon", 
	"data.db.drinkroom",
	"data.db.familysplv",
	"data.db.itemsource",
	"data.db.spiritattr",
	"data.db.spiritexp",
	"data.db.country",
	"data.db.exploitshop",
	"data.db.feats",
	"data.db.wishreward",
    "data.db.cardweapon"  , 
    "data.db.cardraiselevel"  ,  
    "data.db.cardraise"  , 
    "data.db.stagepower" ,
    "data.db.daytaskreward",
    "data.db.familyupgrade",
    "data.db.familyactive",
    "data.db.familygoods",
    "data.db.familylvreward",
    "data.db.familyskill",
    "data.db.familyskillattr",
    "data.db.groupbuyreward",
    "data.db.cardwaken",
    "data.db.worldbossreward",
    "data.db.worldbossconfig",
    "data.db.worldbosskillreward",
    "data.db.familywincount",
    "data.db.worlddan",
    "data.db.worlddanreward",
    "data.db.honor",
    "data.db.worldmatchreward",
    "data.db.worldrankreward",
    "data.db.worldshop",
    "data.db.share",
    "data.db.signiapreward",
    "data.db.familyselv",
    "data.db.dragonballshop",
    "data.db.familydonateitem",
    --"data.db.towerconfig",
    --"data.db.towermonster",
    --"data.db.towershop",
    --"data.db.towerreward",
    "data.db.townshop",
    "data.db.townreward",
    "data.db.townconfig",
    "data.db.townmonster",
    "data.db.daytaskact",
    "data.db.mineeventshop",
    "data.db.stageflop",
    "data.db.treasure_quench",
    "data.db.treasure_suit",
    "data.db.treasure_upgrade",
    "data.db.treasure",
    "data.db.treasureupdatemaster",
    "data.db.cardraisepower",
    "data.db.recruit_mate",
    "data.db.emotionshop",
    "data.db.minechapterinfo",
    "data.db.minestagedraw",
    "data.db.replaceitem",
    "data.db.familyoretier",
    "data.db.familyorelv",
    "data.db.familymembertypeinfo",
    "data.db.familystageconf",
    "data.db.familystagebufflv",
    "data.db.familystagebuffup",
    "data.db.familystagereward",
    "data.db.cteventinfo",
    "data.db.ctweatherinfo",
    "data.db.ctterraininfo",
    "data.db.lootfoodachireward",
    "data.db.lootfoodrankreward",
    "data.db.ctnotice",
    "data.db.richmanconfig",
    "data.db.richmanrankreward",
    "data.db.richmanscorereward",
    "data.db.circle",
    "data.db.circleadd",
    "data.db.constellation",
    "data.db.constellationgroup",
    "data.db.constellationachieve",
    "data.db.constellation_stage",
    "data.db.treasurestarbuff",
    "data.db.treasurestar",
    "data.db.petspecialtalent",
    "data.db.cavebox",

	"TownPanel=view.town.townPanel", 
	"TownDiffPanel=view.town.townDiffPanel", 
	"TownResultPanel=view.town.townResultPanel", 
	"TownSweepPanel=view.town.townSweepPanel", 
	"TownSweepItem=view.town.townSweepItem", 
	"TownRewardPanel=view.town.townRewardPanel", 
	"TownAddAttrPanel=view.town.townAddAttrPanel", 
	"TownAddAttrItem=view.town.townAddAttrItem", 
	"TownGiftPanel=view.town.townGiftPanel", 

	"DragonLayer=view.drawcard.dragonLayer",
	"Dragon3D=view.drawcard.dragon3D",
	"Main3D=view.main.main3D",
	"DragonUI=view.drawcard.dragonUI",
	"DrawCardBoxPanel=view.drawcard.drawCardBoxPanel",

	"MainLayer=view.main.mainLayer",
	"MainMoneyLayer=view.main.mainMoneyLayer",
	"MainBgCoverLayer=view.main.mainBgCoverLayer",
	"MainBgLayer=view.main.mainBgLayer",	
	"MapNamePanel=view.main.mapNamePanel",	

	"UserInfoPanel=view.main.userInfoPanel",
	"UserChangeIconPanel=view.main.userChangeIconPanel",
	"UserIconItem=view.main.userIconItem",
	"UserIconFrameItem=view.main.userIconFrameItem",
	"UserSetPanel=view.main.userSetPanel",
	"UserExchangePanel=view.main.userExchangePanel",
	"UserBindEmailPanel=view.main.userBindEmailPanel",
	"LanguageSetPanel=view.main.languageSetPanel",	
	"UserHaloPanel=view.main.userHaloPanel",
	"UserHaloItem=view.main.userHaloItem",
	"UserHaloItem2=view.main.userHaloItem2",

	"CardInfoPanel=view.card.cardInfoPanel",
	"CardInfoProPanel=view.card.cardInfoProPanel",
	"CardInfoSkillPanel=view.card.cardInfoSkillPanel",
	"CardInfoEquipPanel=view.card.cardInfoEquipPanel",
	"CardInfoRelationPanel=view.card.cardInfoRelationPanel" ,
	"CardInfoRelationItem=view.card.cardInfoRelationItem" ,
	"CardLevelUpPanel=view.card.cardLevelUpPanel" ,
	"NewRelationPanel=view.card.newRelation" ,
	"CardAwakePreviewPanel=view.card.cardAwakePreviewPanel" ,

	"TipEquipItem=view.common.tipEquipItem" ,
	"TipTouchPetTalentSkill=view.common.tipTouchPetTalentSkill",
	"TipEquipItemGet=view.common.tipEquipItemGet" ,
	"TipEquipItemCompound=view.common.tipEquipItemCompound" ,
	"FormationPanel=view.common.formationPanel" ,
	"FormationCardItem=view.common.formationCardItem" ,
	"TipShopItem=view.common.tipShopItem" ,
    "TipTouchSkill=view.common.tipTouchSkill" ,
    "TipTouchDesc=view.common.tipTouchDesc" ,
	"TipTouchCooperateSkill=view.common.tipTouchCooperateSkill" ,
	"TipTouchEquipItem=view.common.tipTouchEquipItem" ,
	"TipTouchMyFriend=view.common.tipTouchMyFriend" ,
	"TipTouchChatRole=view.common.tipTouchChatRole" ,
	"TipFriendInfo=view.common.tipFriendInfo" ,
	"TipTouchCountry=view.common.tipTouchCountry" ,
	"RulePanel=view.common.rulePanel",
	"AppStoreConfirmPanel=view.common.appStoreConfirmPanel",
	"AdvertisePanel=view.common.agPublicPanel",

	"AtlasCrusadeFinalPanel=view.atlas.atlasCrusadeFinalPanel" ,
	"AtlasCrusadeSweepItem=view.atlas.atlasCrusadeSweepItem" ,
	"AtlasCrusadeSweepFinalPanel=view.atlas.atlasCrusadeSweepFinalPanel" ,
	"AtlasWorldBossFinalPanel=view.atlas.atlasWorldBossFinalPanel" ,
	"AtlasPanel=view.atlas.atlasPanel" ,
	"AtlasEnterPanel=view.atlas.atlasEnterPanel" ,
	"AtlasFormationPanel=view.atlas.atlasFormationPanel" ,
	"AtlasFormationItem=view.atlas.atlasFormationItem" ,
	"AtlasFormationRole=view.atlas.atlasFormationRole" ,
	"AtlasItem=view.atlas.atlasItem" ,
	"AtlasAutoPanel=view.atlas.atlasAutoPanel" ,
	"AtlasAutoItem=view.atlas.atlasAutoItem" ,
	"AtlasRewardBoxPanel=view.atlas.atlasRewardBox" ,

	"AtlasDropPanel=view.atlas.atlasDropPanel" ,
	"AtlasStatus=view.atlas.atlasStatus" ,
	"AtlasDropItem=view.atlas.atlasDropItem" ,
	"DropItem=view.atlas.dropItem",
	"LostStrengthenItem=view.atlas.lostStrengthenItem",
	"ExpBar=view.common.expBar",

	"AtlasFinalPanel=view.atlas.atlasFinalPanel" ,
	"AtlasActFinalPanel=view.atlas.atlasActFinalPanel" ,
	"AtlasCompletePanel=view.atlas.atlasCompletePanel",

    "view.battle.battleCallBack",
    "view.battle.battleParseEvent",
	"BattleLayer=view.battle.battleLayer",
	"BattleRole=view.battle.battleRole",
	"BattleTalk=view.battle.battleTalk",
	"BattleRoleBlood=view.battle.battleRoleBlood",
	"BattlePausePanel=view.battle.battlePausePanel",
	"DrawCardPanel=view.drawcard.drawCardPanel",
	"SoulListPanel=view.drawcard.soulListPanel",

	"CrusadeBuyTimePanel=view.crusade.crusadeBuyTimePanel",
	"CrusadeEnterPanel=view.crusade.crusadeEnterPanel",
	"CrusadeItem=view.crusade.crusadeItem",
	"CrusadeNewPanel=view.crusade.crusadeNewPanel",
	"CrusadePanel=view.crusade.crusadePanel",
	"CrusadeShopPanel=view.crusade.crusadeShopPanel",

	"CrusadeFeatItem=view.crusade.crusadeFeatItem",
	"CrusadeFeatPanel=view.crusade.crusadeFeatPanel",
	"CrusadeCallItem=view.crusade.crusadeCallItem",
	"CrusadeCallPanel=view.crusade.crusadeCallPanel",
	"CrusadeCallFlaPanel=view.crusade.crusadeCallFlaPanel",

	"BagItem=view.bag.bagItem",
	"BagPanel=view.bag.bagPanel",
	"MultiItemOpenBoxPanel=view.bag.multiItemOpenBoxPanel",
	"MulitItemBox=view.bag.mulitItemBox",
	"ItemSellPanel=view.bag.itemSellPanel",

	"TaskItem=view.task.taskItem",
	"Task7DayItem=view.task.task7DayItem",
	"TaskPanel=view.task.taskPanel",
	"TaskRewardBoxPanel=view.task.taskRewardBoxPanel",
	"NewTaskPanel=view.task.newTaskPanel",
	"Task7DayPanel=view.task.task7DayPanel",

    "ShopItem3=view.shop.shopItem3", 
    "ShopPanel3=view.shop.shopPanel3",
    
	"ShopItem=view.shop.shopItem",
	"ShopBuyItemPanel=view.shop.shopBuyItemPanel",
	"ShopPanel=view.shop.shopPanel",
	"ShopBuyAllPanel=view.shop.shopBuyAllPanel",
	"FamilyShop2Item=view.shop.familyShop2Item",
	"FamilyShop3Item=view.shop.familyShop3Item",
	"FamilyShop4Item=view.shop.familyShop4Item",
	"TowerShopRewardItem=view.shop.towerShopRewardItem",
	"MallMenuItem=view.shop.mallMenuItem",
    "MallPanel=view.shop.mallPanel",
    "MallPayPanel=view.shop.mallPayPanel",
	"VipGiftItem=view.shop.vipGiftItem",
	"VipDayGiftItem=view.shop.vipDayGiftItem",
	"WeekGiftItem=view.shop.weekGiftItem",
	"ShopNoticePanel=view.shop.shopNoticePanel",

	"SigninItem=view.signin.signinItem",
	"SigninVipItem=view.signin.signinVipItem",
	"SigninPanel=view.signin.signinPanel",

	"MailItem=view.mail.mailItem",
	"MailPanel=view.mail.mailPanel",
	"MailWritePanel=view.mail.mailWritePanel",
	"FriendListPanel=view.friend.friendListPanel",
	"FriendListItem=view.friend.friendListItem",

	"PetItem=view.pet.petItem",
	"PetPanel=view.pet.petPanel",
	"PetRelationPanel=view.pet.petRelationPanel" ,
	"PetRelationItem=view.pet.petRelationItem" ,

	"PetTowerPanel=view.pet.petTowerPanel",
	"PetTowerAtlasItem=view.pet.petTowerAtlasItem",
	"PetTowerBoxPanel=view.pet.petTowerBoxPanel",
	"PetTowerBoxInfoPanel=view.pet.petTowerBoxInfoPanel",
	"PetTowerBoxInfoItem=view.pet.petTowerBoxInfoItem",
	"PetTowerBoxOpenPanel=view.pet.petTowerBoxOpenPanel",
	"PetNoticePanel=view.pet.petNoticePanel",
    "PetAwakePreviewPanel=view.pet.petAwakePreviewPanel",
    "PetAwakePreviewItem=view.pet.petAwakePreviewItem",

	"ActivityItem=view.activity.activityItem",
	"ActivityPanel=view.activity.activityPanel",
	"ActivityAllPanel=view.activity.activityAllPanel",
	"ActivityMenuItem=view.activity.activityMenuItem",
	"Activity7DayPanel=view.activity.activity7DayPanel",
	"Activity7DayItem=view.activity.activity7DayItem",
	"ActivityLevelUpPanel=view.activity.activityLevelUpPanel",
	"ActivityLevelUpItem=view.activity.activityLevelUpItem",
	"ActivityTaskDayPanel=view.activity.activityTaskDayPanel",
	"ActivityTaskDayItem=view.activity.activityTaskDayItem",

	"ActivityInvestPanel=view.activity.activityInvestPanel",
	"ActivityInvestItem=view.activity.activityInvestItem",
	"ActivityInvest2Panel=view.activity.activityInvest2Panel",
	"ActivityInvest2Item=view.activity.activityInvest2Item",

    "ActivityXiaoChuGiftPanel=view.activity.activityXiaoChuGiftPanel",
	"ActivitySaleOffPanel=view.activity.activitySaleOffPanel",
	"ActivitySaleOffItem=view.activity.activitySaleOffItem",
	"ActivityIapCard=view.activity.activityIapCardPanel",
	"ActivityPayPanel=view.activity.activityPayPanel",
	"ActivityConsumePanel=view.activity.activityConsumePanel" ,
	"ActivityPayBoxPanel=view.activity.activityPayBoxPanel" ,
	"ActivityAtlasDoublePanel=view.activity.activityAtlasDoublePanel" ,
	"ActivityDrawCardPanel=view.activity.activityDrawCardPanel" ,
	"ActivityPayBox3Panel=view.activity.activityPayBox3Panel" ,
	"ActivityCatPanel=view.activity.activityCatPanel",
	"ActivityCatNewPanel=view.activity.activityCatNewPanel",
	"ActivityVipPanel=view.activity.activityVipPanel",
	"ActivityWishPanel=view.activity.activityWishPanel",
	"ActivityWishItem=view.activity.activityWishItem",
	"ActivityBuyGoldCriticalPanel=view.activity.buyGoldCriticalPanel",
	"ActivityBuyEnergyLimitPanel=view.activity.buyEnergyLimitPanel",
	"ActivityBathDoublePanel=view.activity.activityBathDoublePanel",
	"ActivityFamilyActPanel=view.activity.activityFamilyActPanel",
	"ActivityDoubleDiaPanel=view.activity.activityDoubleDiaPanel",
	"ActivityItemDropPanel=view.activity.activityItemDropPanel",

    "ActivityPayResetPanel=view.activity.activityPayResetPanel",
    "ActivityBuyEnergySaleOffPanel=view.activity.activityBuyEnergySaleOffPanel",
    "ActivitySaleOffLimitPanel=view.activity.activitySaleOffLimitPanel",
    "ActivityBuyConDiscount=view.activity.activityBuyConDiscount",
    "ActivitySoullifeSaleOffPanel=view.activity.activitySoullifeSaleOffPanel",

    "ActivityExchangePanel=view.activity.activityExchangePanel",
    "ActivityExchangeItem=view.activity.activityExchangeItem" ,
    "ActivityExpenseReturnItem=view.activity.activityExpenseReturnItem",
    "ActivityExpenseReturnPanel=view.activity.activityExpenseReturnPanel" ,
    "ActivityAtlasResetPanel=view.activity.activityAtlasResetPanel" ,
    "ActivityTuanPanel=view.activity.activityTuanPanel",
    "ActivityTuanItem=view.activity.activityTuanItem",
    "ActivityTuanRewardPanel=view.activity.activityTuanRewardPanel",
    "ActivityTuanRewardItem=view.activity.activityTuanRewardItem",
    "ActivityEnargyPanel=view.activity.activityEnargyPanel",
    "ActivityEnargyBoxPanel=view.activity.activityEnargyBoxPanel",
    "ActivityVipExperiencePanel=view.activity.activityVipExperiencePanel",
    
    "ActivitySharePanel=view.activity.activitySharePanel",
    "ActivityShareItem=view.activity.activityShareItem",
    "ActivitySignPanel=view.activity.activitySignPanel",
    "ActivitySignItem=view.activity.activitySignItem",
    "ActivitySnatchPanel=view.activity.activitySnatchPanel",
    "Activity17Panel=view.activity.activity17Panel",
    "Activity17Item=view.activity.activity17Item",
    "Activity19Panel=view.activity.activity19Panel",
    "ActivityNewYearEnergyPanel=view.activity.activityNewYearEnergyPanel",
    "ActivityFreeVipPanel=view.activity.activityFreeVipPanel",
    "ActivityFreeVipItem=view.activity.activityFreeVipItem",
    "ActivityRecruitPanel=view.activity.activityRecruitPanel",
    "ActivityRecruitItem=view.activity.activityRecruitItem",
    "ActivityRecruitSharePanel=view.activity.activityRecruitSharePanel",
    "ActivityRankPanel=view.activity.activityRankPanel",
    "ActivityRankItem=view.activity.activityRankItem",
    "ActivityLoginRewardPanel=view.activity.activityLoginRewardPanel",
    "ActivityLoginRewardItem=view.activity.activityLoginRewardItem",

    "ActivityMultiItemPanel=view.activity.activityMultiItemPanel",
    "ActivityMultiItem=view.activity.ActivityMultiItem",

	"ActivityChargeReturnItem=view.activity.activityChargeReturnItem",
	"ActivityChargeReturnPanel=view.activity.activityChargeReturnPanel",
	"ChatFriendItem=view.chat.chatFriendItem",
	"ChatItem=view.chat.chatItem",
	"ChatItem2=view.chat.chatItem2",
	"ChatPanel=view.chat.chatPanel",
	"ChatVoiceItem=view.chat.chatVoiceItem",

	"NewCardSharePanel=view.share.newCardSharePanel",
	"PetSharePanel=view.share.petSharePanel",
	"FormationSharePanel=view.share.formationSharePanel",
	"LevelUpSharePanel=view.share.levelUpSharePanel",

	"FriendPanel=view.friend.friendPanel",
	"FriendAddPanel=view.friend.friendAddPanel",
	"FriendInfoPanel=view.friend.friendInfoPanel",
	"FriendSignPanel=view.friend.friendSignPanel",
	"FindFriendItem=view.friend.findFriendItem",


	"CardItem=view.card.cardItem",
	"CardSkillItem=view.card.cardSkillItem",
	"CardPanel=view.card.cardPanel",
	"CardSkillLevelUpPanel=view.card.cardSkillLevelUpPanel",

	"ArenaPanel=view.arena.arenaPanel",

	"PayPanel=view.pay.payPanel",
	"FirstPayPanel=view.pay.firstPayPanel",
	"FirstPayVideoPanel=view.pay.firstPayVideoPanel",

	"VipPanel=view.vip.vipPanel",
	"VipItem=view.vip.vipItem",
	"VipItemDetail=view.vip.vipItemDetail",
	"VipBuyTimesPanel=view.vip.vipBuyTimesPanel",
	"VipLevelupPanel=view.vip.vipLevelupPanel",
	"VipNoticePanel=view.vip.vipNoticePanel",

	"FamilyBgPanel=view.family.familyBgPanel",
	"FamilyHeadPanel=view.family.familyHeadPanel",
	"FamilySearchItem=view.family.familySearchItem",
	"FamilyCreatePanel=view.family.familyCreatePanel",
	"FamilySearchPanel=view.family.familySearchPanel",
	"FamilyHomePanel=view.family.familyHomePanel",
	"FamilyMemItem=view.family.familyMemItem",
	"FamilyMamagePanel=view.family.familyMemagePanel",
	"FamilyApplyItem=view.family.familyApplyItem",
	"DynamicMenuPanel = view.family.DynamicMenuPanel",
	"FamilyModuleItem=view.family.familyModuleItem",
	"FamilyContributionPanel=view.family.familyContributionPanel",
	"FamilyEggPanel=view.family.familyEggPanel",
	"FamilyContributionItem=view.family.familyContributionItem",
	"FamilySpringPanel=view.family.familySpringPanel",
	"FamilySevenPanel=view.family.familySevenPanel",
	"FamilyHDEnterPanel=view.family.familyHDEnterPanel",
	"FamilyHDItem=view.family.familyHDItem",
	"FamilyMoBaiPanel=view.family.familyMoBaiPanel",
	"FamilyChNamePanel=view.family.familyChNamePanel",
	"FamilyHallPanel=view.family.familyHallPanel",
	"FamilyActiveBoxPanel=view.family.familyActiveBoxPanel",
	"FamilyOtherFamilyInfoPanel=view.family.familyOtherFamilyInfoPanel",
	"FamilySkillPanel=view.family.familySkillPanel",
	"FamilySkillItem=view.family.familySkillItem",
	"FamilyUserSkillPanel=view.family.familyUserSkillPanel",
	"FamilyUserSkillItem=view.family.familyUserSkillItem",
	"FamilyDynamicPanel=view.family.familyDynamicPanel",
	"FamilyDynamicItem=view.family.familyDynamicItem",
	"FamilyOrePanel=view.family.familyOrePanel",
	"FamilyOreItem=view.family.familyOreItem",
	"FamilyOreRecordPanel=view.family.familyOreRecordPanel",
	"FamilyOreRecordItem=view.family.familyOreRecordItem",
	"FamilyMemTitlePanel=view.family.familyMemTitlePanel",
	"FamilyExpRankPanel=view.family.familyExpRankPanel",
	"FamilyExpRankItem=view.family.familyExpRankItem",

	"FamilyDonateCardPanel=view.familydonate.familyDonateCardPanel",
	"FamilyDonateCardItem=view.familydonate.familyDonateCardItem",
	"FamilyDonateListPanel=view.familydonate.familyDonateListPanel",
	"FamilyDonateListItem=view.familydonate.familyDonateListItem",
	

	"BathPanel = view.bath.bathPanel",
	"BathDetailPanel = view.bath.bathDetailPanel",
	"BathMolestPanel = view.bath.bathMolestPanel",

	"TrainRoomPanel = view.trainroom.trainRoomPanel",
	"TrainSingleRoomPanel = view.trainroom.trainSingleRoomPanel",
	"TrainMultiRoomPanel = view.trainroom.trainMultiRoomPanel",
	"TrainMultiRoomItem = view.trainroom.trainMultiRoomItem",
	"TrainRoomProtectPanel = view.trainroom.trainRoomProtectPanel",
	"TrainRoomQiangPanel = view.trainroom.trainRoomQiangPanel",

	"ArenaRecordPanel=view.arena.arenaRecordPanel",
	"ArenaRecordItem=view.arena.arenaRecordItem",
	"ArenaRankPanel=view.arena.arenaRankPanel",
	"ArenaRankItem=view.arena.arenaRankItem",
	"ArenaRankMenuItem=view.arena.arenaRankMenuItem",
	"ArenaRulePanel=view.arena.arenaRulePanel",

	"UnlockPanel=view.unlock.unlockPanel",

	"GlobalBuyPanel=view.common.globalBuyPanel",
	"BuyGoldPanel=view.main.buyGoldPanel",
	"EnergyBuyPanel=view.common.energyBuyPanel",
	"LevelUpPanel=view.common.levelupPanel",
	"LevelUpItem=view.common.levelupItem",
	"CardUpQualityPanel=view.common.cardUpQualityPanel",
	"NewCardPanel=view.common.newCardPanel",
	"SetNamePanel=view.common.setNamePanel",

	"XunXianItem=view.soullife.xunXianItem",
	"SpiritIntroPanel=view.soullife.spiritIntroPanel",
	"SoulLifeFormationPanel=view.soullife.soulLifeFormationPanel",
	"SpiritQuickPanel=view.soullife.spiritQuickPanel",
	"SoulLifeDetailPanel=view.soullife.soulLifeDetailPanel",
	"SoulLifeEquipPanel=view.soullife.soulLifeEquipPanel",
	"SoulLifeEquipItem=view.soullife.soulLifeEquipItem",
	"SoulLifeUpgradePanel=view.soullife.soulLifeUpgradePanel",
	"SoulLifeAutoChoosePanel=view.soullife.soulLifeAutoChoosePanel",
	"SoulLifeFraItem=view.soullife.soulLifeFraItem",
	"SoulLifeFraExchangePanel=view.soullife.soulLifeFraExchangePanel",
	"SoulLifeCallShenPanel=view.soullife.soulLifeCallShenPanel",
	"SoullifeBaoliRewardPanel=view.soullife.soullifeBaoliRewardPanel",
	"TipTouchSoullifeAttrPanel=view.soullife.tipTouchSoullifeAttrPanel",

	"GiftPanel = view.gift.giftPanel",
	"OnlineGiftPanel = view.gift.onlineGiftPanel",
	"FeedbackPanel = view.common.feedbackPanel",
	"FeedbackGTPanel = view.common.feedbackGTPanel",
	"FeedbackItemPanel = view.common.feedbackItemPanel",
	"BuyGoldItem = view.main.buyGoldItem",
	"DigMinePanel = view.digmine.digMinePanel",
	"MineDepotPanel = view.digmine.mineDepotPanel",
	"MineToolItem = view.digmine.mineToolItem",
	"MineWorkshopPanel = view.digmine.mineWorkshopPanel",
	"MineMapLayer = view.digmine.mineMapLayer",
    "WeaponEquipSoulPanel = view.weapon.weaponEquipSoulPanel", 
    "WeaponRaisePanel  = view.weapon.weaponRaisePanel" ,
    "view.weapon.weaponRaiseUpgradePanel", 
    "view.weapon.weaponRaiseAttrPanel", 
    "WeaponRaiseItem = view.weapon.weaponRaiseItem" ,
    "WeaponEquipSoulItem = view.weapon.weaponEquipSoulItem" ,
    "WeaponRaiseVipPanel = view.weapon.weaponRaiseVipPanel" ,

    "WeaponPreviewPanel = view.weapon.weaponPreviewPanel" ,
    "WeaponPreviewItem = view.weapon.weaponPreviewItem" ,
    "WeaponTransmitCardItem = view.weapon.weaponTransmitCardItem" ,
    "WeaponTransmitBuffItem = view.weapon.weaponTransmitBuffItem" ,
    "WeaponTransmitCardPanel = view.weapon.weaponTransmitCardPanel" ,
    "WeaponTransmitInfoPanel = view.weapon.weaponTransmitInfoPanel" ,
    "WeaponTransmitPanel = view.weapon.weaponTransmitPanel" ,
    "WeaponTransmitResultPanel = view.weapon.weaponTransmitResultPanel" ,
    "WeaponExchangeResultPanel=view.weapon.weaponExchangeResultPanel",
    
    "MineProjectItem = view.digmine.mineProjectItem",
    "MineNewProjPanel = view.digmine.mineNewProjPanel",
    "MineDigEffectNode = view.digmine.mineDigEffectNode",
    "MineExchangePanel = view.digmine.mineExchangePanel",
    "MineExchangeItem = view.digmine.mineExchangeItem",
    "MineExchangeBox = view.digmine.mineExchangeBox",
    "MineMermaidBuyPanel = view.digmine.mineMermaidBuyPanel",
    "MineLuckyWheelPanel = view.digmine.mineLuckyWheelPanel",
    "MineBlackMarketPanel = view.digmine.mineBlackMarketPanel",
    "MineTradeItem = view.digmine.mineTradeItem" ,
    "MineMermaidRewardPanel = view.digmine.mineMermaidRewardPanel",
    "MinePickaxSupplementPanel = view.digmine.minePickaxSupplementPanel",
    "MineBuyMinerPanel = view.digmine.mineBuyMinerPanel",
    "MineAtlasPanel = view.digmine.mineAtlasPanel",
    "MineAtlasItem = view.digmine.mineAtlasItem",
    "MineAtlasDetailPanel = view.digmine.mineAtlasDetailPanel",
    "MineDrawLotsPanel = view.digmine.mineDrawLotsPanel",
    "MineAtlasBoxPanel = view.digmine.mineAtlasBoxPanel",
    "MineAtlasEndBoxPanel = view.digmine.mineAtlasEndBoxPanel",
    "MineAtlasSweepPanel = view.digmine.mineAtlasSweepPanel",
    "MineDigIconItem = view.digmine.mineDigIconItem",

    "WorldBossPanel = view.worldboss.worldBossPanel",
    "WorldBossItem = view.worldboss.worldBossItem",
    "WorldBossRewardPanel = view.worldboss.worldBossRewardPanel",
    "WorldBossRewardItem = view.worldboss.worldBossRewardItem",
    "WorldBossRankPanel = view.worldboss.worldBossRankPanel",
  	"AtlasWorldBossRewardlPanel = view.worldboss.atlasWorldBossRewardlPanel",

    "FamilyWarEditItem = view.familywar.familyWarEditItem",
    "FamilyWarEditPanel = view.familywar.familyWarEditPanel",
    "FamilyWarMatchPanel = view.familywar.familyWarMatchPanel",
    "FamilyWarSignUpPanel = view.familywar.familyWarSignUpPanel",
    "FamilyWarSupportRecord = view.familywar.familyWarSupportRecord",
    "FamilyWarSupportItem = view.familywar.familyWarSupportItem",
    "FamilyWarSupportPanel = view.familywar.familyWarSupportPanel",
    "FamilyWarSupportVipPanel = view.familywar.familyWarSupportVipPanel",
    "FamilyWarRewardPanel = view.familywar.familyWarRewardPanel",
    "FamilyWarRankItem = view.familywar.familyWarRankItem",
    "FamilyWarRankPanel = view.familywar.familyWarRankPanel",

    "FamilyWarRewardItem = view.familywar.familyWarRewardItem",
    
    "FamilyWarMatchDetailPanel = view.familywar.familyWarMatchDetailPanel",
    "FamilyWarMatchRecordItem = view.familywar.familyWarMatchRecordItem", 

    "FamilyWarPlayBigItem = view.familywar.familyWarPlayBigItem", 
    "FamilyWarPlaySmallItem = view.familywar.familyWarPlaySmallItem", 
    
    "CardTransmitPanel=view.transmit.cardTransmitPanel",
    "CardExchangePanel=view.transmit.cardExchangePanel",
    "TransmitPanel=view.transmit.transmitPanel",
    "CardTransmitCardItem=view.transmit.cardTransmitCardItem",
    "CardTransmitResultPanel=view.transmit.cardTransmitResultPanel",

    "TreasureTransmitItem=view.transmit.treasureTransmitItem",
    "TreasureTransmitPanel=view.transmit.treasureTransmitPanel",
    "TreasureTransmitSelItem=view.transmit.treasureTransmitSelItem",
    "TreasureTransmitSelPanel=view.transmit.treasureTransmitSelPanel",

    "MulitOpenBoxPanel=view.bag.mulitOpenBoxPanel",
    "AtlasNoticePanel=view.atlas.atlasNoticePanel",
    
    "ServerBattleMainPanel = view.serverBattle.serverBattleMainPanel",
    "ServerBattleRewardIntroPanel = view.serverBattle.serverBattleRewardIntroPanel",
    "ServerBattleRewardPanel = view.serverBattle.serverBattleRewardPanel",
    "ServerBattleFindRivalPanel = view.serverBattle.serverBattleFindRivalPanel",
	"ServerBattleRankPanel = view.serverBattle.serverBattleRankPanel",
	"ServerBattleRankItem = view.serverBattle.serverBattleRankItem",
	"ServerBattleMatchPanel = view.serverBattle.serverBattleMatchPanel",
	"ServerBattleSecRewardItem = view.serverBattle.serverBattleSecRewardItem",
	"ServerBattleFormationPanel = view.serverBattle.serverBattleFormationPanel",
	"ServerBattleBasicInfoPanel = view.serverBattle.serverBattleBasicInfoPanel",
	"ServerBattleFinalPanel = view.serverBattle.serverBattleFinalPanel",
	"ServerBattleBgPanel = view.serverBattle.serverBattleBgPanel",
	"ServerBattleMatchRewardItem = view.serverBattle.serverBattleMatchRewardItem",
	"ServerBattlePreviewPanel = view.serverBattle.serverBattlePreviewPanel",
	"view.serverBattle.serverBattleConst",
    "ServerBattleLookVideoPanel = view.serverBattle.serverBattleLookVideoPanel",

    "BattleDataPanel=view.battle.battleDataPanel",
    "AtlasBoxNoticePanel=view.atlas.atlasBoxNoticePanel",
    "AtlasBoxNoticeItem=view.atlas.atlasBoxNoticeItem",
    "ActivitySign7Panel=view.activity.activitySign7Panel",
    "ActivitySign7Item=view.activity.activitySign7Item",
    "ActivitySign7BoxPanel=view.activity.activitySign7BoxPanel", 

    "ActivitySign7BoxPanel=view.activity.activitySign7BoxPanel", 
    "ActivityRedPackagePanel=view.activity.activityRedPackagePanel", 
    "ActivityRedPackageItem=view.activity.activityRedPackageItem", 
    "ActivityBoxPanel=view.activity.activityBoxPanel",

    "RedPackagePanel=view.redpackage.redPackagePanel", 
    "RedPackageItem=view.redpackage.redPackageItem", 
    "RedPackageDetailPanel=view.redpackage.redPackageDetailPanel", 
    "RedPackageDetailItem=view.redpackage.redPackageDetailItem", 
    "RedPackageRainPanel=view.redpackage.redPackageRainPanel", 
    "RedPackageRewardPanel=view.redpackage.redPackageRewardPanel", 
    "RedPackageBoxPanel=view.redpackage.redPackageBoxPanel", 

    "TreasurePanel=view.treasure.treasurePanel", 
    "TreasureBagItem=view.treasure.treasureBagItem", 
    "TipTreasure=view.treasure.tipTreasure", 
    "TreasureDecomposePanel=view.treasure.treasureDecomposePanel", 
    "TreasureStarDes=view.treasure.treasureStarDes", 
    "TreasureStarDesItem=view.treasure.treasureStarDesItem", 
    
    "view.treasure.treasureUpgradePanel", 
    "view.treasure.treasureQuenchPanel", 
    "view.treasure.treasureRiseStarPanel", 
    "TreasureEquipSoulItem=view.treasure.treasureEquipSoulItem",
    "view.treasure.treasureBagPanel", 
    "TreasureWenYaoPanel=view.treasure.treasureWenYaoPanel", 
    "TreasureOneKeyDecom=view.treasure.treasureOneKeyDecom", 
    "TreasureBuyTimes=view.treasure.treasureBuyTimes", 
    "TreasureQuenchOneKeyPanel=view.treasure.treasureQuenchOneKeyPanel",
    "TipTouchRaise=view.common.tipTouchRaise", 
    

    "ActivityLuckWheelPanel=view.luckwheel.activityLuckWheelPanel",
    "LuckWheelRewardPanel=view.luckwheel.luckWheelRewardPanel",
    "LuckWheelRewardItem=view.luckwheel.luckWheelRewardItem",
    "LuckWheelLogPanel=view.luckwheel.luckWheelLogPanel",
    "LuckWheelLogItem=view.luckwheel.luckWheelLogItem",
    
    "CardSoulPanel=view.transmit.cardSoulPanel",
    "CardSoulBuyItem=view.transmit.cardSoulBuyItem",
    "AtlasCompleteCgPanel=view.atlas.atlasCompleteCgPanel",

    "FamilyStageMainPanel=view.familystage.familyStageMainPanel",
    "FamilyStageItem=view.familystage.familyStageItem",
    "FamilyStageBuffPanel=view.familystage.familyStageBuffPanel",
    "FamilyStageBuffUpPanel=view.familystage.familyStageBuffUpPanel",
    "FamilyStageJoinPanel=view.familystage.familyStageJoinPanel",
    "FamilyStageJoinItem=view.familystage.familyStageJoinItem",
    "FamilyStageLastRankPanel=view.familystage.familyStageLastRankPanel",
    "FamilyStageLastRankItem=view.familystage.familyStageLastRankItem",
    "FamilyStageRewardPanel=view.familystage.familyStageRewardPanel",
    "FamilyStageRewardItem=view.familystage.familyStageRewardItem",
    "FamilyStageFormationPanel=view.familystage.familyStageFormationPanel",
    "FamilyStageBuffItem=view.familystage.familyStageBuffItem",
    "FamilyStageHarmRankPanel=view.familystage.familyStageHarmRankPanel",
    "TipFamilyStageChaRecPanel=view.familystage.tipFamilyStageChaRecPanel",

    "HuntItem=view.main.huntItem",
    "HuntPanel=view.main.huntPanel",
    "TreasureHuntGroupChoosePanel=view.treasureHunt.treasureHuntGroupChoosePanel",
    "TreasureHuntTeamFormationPanel=view.treasureHunt.treasureHuntTeamFormationPanel",
    "TreasureHuntTeamItem=view.treasureHunt.treasureHuntTeamItem",
    "TreasureHuntEnterPanel=view.treasureHunt.treasureHuntEnterPanel",
	"TreasureHuntChooseMapPanel=view.treasureHunt.treasureHuntChooseMapPanel",
	"TreasureHuntNoticeItem=view.treasureHunt.treasureHuntNoticeItem",
	"TreasureHuntNoticePanel=view.treasureHunt.treasureHuntNoticePanel",
	"TreasureHuntAmbushDetailPanel=view.treasureHunt.treasureHuntAmbushDetailPanel",
	"TreasureHuntProgressDetailPanel=view.treasureHunt.treasureHuntProgressDetailPanel",
	"TreasureHuntStageRecordPanel=view.treasureHunt.treasureHuntStageRecordPanel",
	"TreasureHuntRecordPanel=view.treasureHunt.treasureHuntRecordPanel",
	"TreasureHuntRecordItem=view.treasureHunt.treasureHuntRecordItem",
	"TipTouchTreasureHuntSpeaker=view.treasureHunt.tipTouchTreasureHuntSpeaker",
	"TreasureHuntSpeakerPanel=view.treasureHunt.treasureHuntSpeakerPanel",
    "TreasureHuntEventItem=view.treasureHunt.treasureHuntEventItem",
    "TreasureHuntEventItem1=view.treasureHunt.treasureHuntEventItem1",

	"FoodFightPanel=view.foodfight.foodFightPanel",
	"FoodFightAchiPanel=view.foodfight.foodFightAchiPanel",
	"FoodFightAchiItem=view.foodfight.foodFightAchiItem",
	"FoodFightRankPanel=view.foodfight.foodFightRankPanel",
	"FoodFightRecordPanel=view.foodfight.foodFightRecordPanel",
	"FoodFightRecordItem=view.foodfight.foodFightRecordItem",

    "ConstellationMainPanel=view.constellation.constellationMainPanel",
    "ConstellationItem=view.constellation.constellationItem",
    "ConstellationBagPanel=view.constellation.constellationBagPanel",
    "ConstellationBagItem=view.constellation.constellationBagItem",
    "ConstellationItemDetailPanel=view.constellation.constellationItemDetailPanel",
    "ConstellationSelectCirclePanel=view.constellation.constellationSelectCirclePanel",
    "ConstellationCircleDetailPanel=view.constellation.constellationCircleDetailPanel",
    "ConstellationGroupItem=view.constellation.constellationGroupItem",
    "ConstellationAchieveInfoPanel=view.constellation.constellationAchieveInfoPanel",
    "ConstellationHuntPanel=view.constellation.constellationHuntPanel",
    "ConstellationSoulPanel=view.constellation.constellationSoulPanel",
    "ConstellationFightPanel=view.constellation.constellationFightPanel",
    "ConstellationSoulItem=view.constellation.constellationSoulItem",
    "ConstellationAchieveItem=view.constellation.constellationAchieveItem",
    "ConstellationGroupStar=view.constellation.constellationGroupStar",
    "ConstellationGroupStarItem=view.constellation.constellationGroupStarItem",

    "RichmanPanel=view.richman.richmanPanel",
    "RichmanShopPanel=view.richman.richmanShopPanel",
    "RichmanRewardPanel=view.richman.richmanRewardPanel",
    "RichmanRewardItem=view.richman.richmanRewardItem",
    "RichmanRankPanel=view.richman.richmanRankPanel",
    "RichmanRankItem=view.richman.richmanRankItem",
    "RichmanRankReward=view.richman.richmanRankReward",
    "RichmanEventPanel=view.richman.richmanEventPanel",
    "RichmanPassPanel=view.richman.richmanPassPanel",
    "TreasureOKDecomposePanel=view.treasure.treasureOKDecomposePanel",


    "PetTalentBookPanel=view.pet.petTalentBookPanel",
    "PetTalentBookItem=view.pet.petTalentBookItem",
    "PetTalentProtPanel=view.pet.petTalentProtPanel",
    "PetTalentLock=view.pet.petTalentLock",
    "CardSelPetPanel=view.card.cardSelPetPanel",
    "CardSelPetItem=view.card.cardSelPetItem",
    "BindPhoneNumPanel=view.login.bindPhoneNumPanel",
    "PetExploreActivityPanel=view.petExplore.petExploreActivityPanel",
    "PetExplorePanel=view.petExplore.petExplorePanel",
    "PetGoldRewardItem=view.petExplore.petGoldRewardItem",
    "PetExploreBoxPanel=view.petExplore.petExploreBoxPanel",
    "view.petExplore.caveCardEvent",
    "PetExploreReplaceCoin=view.petExplore.petExploreReplaceCoin",
    "PetExploreRateBook=view.petExplore.petExploreRateBook",
    "PetCaveTaskPanel=view.petExplore.petCaveTaskPanel",
    "PetCaveBoxOpenPanel=view.petExplore.petCaveBoxOpenPanel",
    "PetTalentReplace=view.pet.petTalentReplace",
    "PetTalentReplaceItem=view.pet.petTalentReplaceItem",
    
    --放在最后
    "replace",
}

startGameInit_table = {	
}